#pragma once

#define MG_ARCH MG_ARCH_CUBE
#define MG_ENABLE_TCPIP 1
#define MG_ENABLE_DRIVER_STM32H 1
#define MG_TCPIP_PHY_ADDR 0
#define MG_DRIVER_MDC_CR 4
#define MG_TLS MG_TLS_NONE
#define MG_OTA MG_OTA_NONE
#define MG_ENABLE_POSIX_FS 0

